services:
  - type: web
    name: chat-bot-backend
    env: node
    rootDir: ./apps/backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: chat-bot-backend
          property: port
